// Languages
export const languages = [
	{ code: "aa", language: "Afar" },
	{ code: "ab", language: "Abkhazian" },
	{ code: "ae", language: "Avestan" },
	{ code: "af", language: "Afrikaans" },
	{ code: "ak", language: "Akan" },
	{ code: "am", language: "Amharic" },
	{ code: "an", language: "Aragonese" },
	{ code: "ar", language: "Arabic" },
	{ code: "as", language: "Assamese" },
	{ code: "av", language: "Avaric" },
	{ code: "ay", language: "Aymara" },
	{ code: "az", language: "Azerbaijani" },
	{ code: "ba", language: "Bashkir" },
	{ code: "be", language: "Belarusian" },
	{ code: "bg", language: "Bulgarian" },
	{ code: "bh", language: "Bihari languages" },
	{ code: "bi", language: "Bislama" },
	{ code: "bm", language: "Bambara" },
	{ code: "bn", language: "Bengali" },
	{ code: "bo", language: "Tibetan" },
	{ code: "br", language: "Breton" },
	{ code: "bs", language: "Bosnian" },
	{ code: "ca", language: "Catalan" },
	{ code: "ce", language: "Chechen" },
	{ code: "ch", language: "Chamorro" },
	{ code: "co", language: "Corsican" },
	{ code: "cr", language: "Cree" },
	{ code: "cs", language: "Czech" },
	{ code: "cu", language: "Church Slavic" },
	{ code: "cv", language: "Chuvash" },
	{ code: "cy", language: "Welsh" },
	{ code: "da", language: "Danish" },
	{ code: "de", language: "German" },
	{ code: "dv", language: "Divehi" },
	{ code: "dz", language: "Dzongkha" },
	{ code: "ee", language: "Ewe" },
	{ code: "el", language: "Greek" },
	{ code: "en", language: "English" },
	{ code: "eo", language: "Esperanto" },
	{ code: "es", language: "Spanish" },
	{ code: "et", language: "Estonian" },
	{ code: "eu", language: "Basque" },
	{ code: "fa", language: "Persian" },
	{ code: "ff", language: "Fulah" },
	{ code: "fi", language: "Finnish" },
	{ code: "fj", language: "Fijian" },
	{ code: "fo", language: "Faroese" },
	{ code: "fr", language: "French" },
	{ code: "fy", language: "Western Frisian" },
	{ code: "ga", language: "Irish" },
	{ code: "gd", language: "Scottish Gaelic" },
	{ code: "gl", language: "Galician" },
	{ code: "gn", language: "Guarani" },
	{ code: "gu", language: "Gujarati" },
	{ code: "gv", language: "Manx" },
	{ code: "ha", language: "Hausa" },
	{ code: "he", language: "Hebrew" },
	{ code: "hi", language: "Hindi" },
	{ code: "ho", language: "Hiri Motu" },
	{ code: "hr", language: "Croatian" },
	{ code: "ht", language: "Haitian" },
	{ code: "hu", language: "Hungarian" },
	{ code: "hy", language: "Armenian" },
	{ code: "hz", language: "Herero" },
	{ code: "ia", language: "Interlingua" },
	{ code: "id", language: "Indonesian" },
	{ code: "ie", language: "Interlingue" },
	{ code: "ig", language: "Igbo" },
	{ code: "ii", language: "Sichuan Yi" },
	{ code: "ik", language: "Inupiaq" },
	{ code: "io", language: "Ido" },
	{ code: "is", language: "Icelandic" },
	{ code: "it", language: "Italian" },
	{ code: "iu", language: "Inuktitut" },
	{ code: "ja", language: "Japanese" },
	{ code: "jv", language: "Javanese" },
	{ code: "ka", language: "Georgian" },
	{ code: "kg", language: "Kongo" },
	{ code: "ki", language: "Kikuyu" },
	{ code: "kj", language: "Kuanyama" },
	{ code: "kk", language: "Kazakh" },
	{ code: "kl", language: "Kalaallisut" },
	{ code: "km", language: "Khmer" },
	{ code: "kn", language: "Kannada" },
	{ code: "ko", language: "Korean" },
	{ code: "kr", language: "Kanuri" },
	{ code: "ks", language: "Kashmiri" },
	{ code: "ku", language: "Kurdish" },
	{ code: "kv", language: "Komi" },
	{ code: "kw", language: "Cornish" },
	{ code: "ky", language: "Kyrgyz" },
	{ code: "la", language: "Latin" },
	{ code: "lb", language: "Luxembourgish" },
	{ code: "lg", language: "Ganda" },
	{ code: "li", language: "Limburgan" },
	{ code: "ln", language: "Lingala" },
	{ code: "lo", language: "Lao" },
	{ code: "lt", language: "Lithuanian" },
	{ code: "lu", language: "Luba-Katanga" },
	{ code: "lv", language: "Latvian" },
	{ code: "mg", language: "Malagasy" },
	{ code: "mh", language: "Marshallese" },
	{ code: "mi", language: "Māori" },
	{ code: "mk", language: "Macedonian" },
	{ code: "ml", language: "Malayalam" },
	{ code: "mn", language: "Mongolian" },
	{ code: "mr", language: "Marathi" },
	{ code: "ms", language: "Malay" },
	{ code: "mt", language: "Maltese" },
	{ code: "my", language: "Burmese" },
	{ code: "na", language: "Nauru" },
	{ code: "nb", language: "Norwegian Bokmål" },
	{ code: "nd", language: "North Ndebele" },
	{ code: "ne", language: "Nepali" },
	{ code: "ng", language: "Ndonga" },
	{ code: "nl", language: "Dutch" },
	{ code: "nn", language: "Norwegian Nynorsk" },
	{ code: "no", language: "Norwegian" },
	{ code: "nr", language: "South Ndebele" },
	{ code: "nv", language: "Navajo" },
	{ code: "ny", language: "Chichewa" },
	{ code: "oc", language: "Occitan" },
	{ code: "oj", language: "Ojibwa" },
	{ code: "om", language: "Oromo" },
	{ code: "or", language: "Odia" },
	{ code: "os", language: "Ossetian" },
	{ code: "pa", language: "Punjabi" },
	{ code: "pi", language: "Pali" },
	{ code: "pl", language: "Polish" },
	{ code: "ps", language: "Pashto" },
	{ code: "pt", language: "Portuguese" },
	{ code: "qu", language: "Quechua" },
	{ code: "rm", language: "Romansh" },
	{ code: "rn", language: "Rundi" },
	{ code: "ro", language: "Romanian" },
	{ code: "ru", language: "Russian" },
	{ code: "rw", language: "Kinyarwanda" },
	{ code: "sa", language: "Sanskrit" },
	{ code: "sc", language: "Sardinian" },
	{ code: "sd", language: "Sindhi" },
	{ code: "se", language: "Northern Sami" },
	{ code: "sg", language: "Sango" },
	{ code: "si", language: "Sinhala" },
	{ code: "sk", language: "Slovak" },
	{ code: "sl", language: "Slovenian" },
	{ code: "sm", language: "Samoan" },
	{ code: "sn", language: "Shona" },
	{ code: "so", language: "Somali" },
	{ code: "sq", language: "Albanian" },
	{ code: "sr", language: "Serbian" },
	{ code: "ss", language: "Swati" },
	{ code: "st", language: "Southern Sotho" },
	{ code: "su", language: "Sundanese" },
	{ code: "sv", language: "Swedish" },
	{ code: "sw", language: "Swahili" },
	{ code: "ta", language: "Tamil" },
	{ code: "te", language: "Telugu" },
	{ code: "tg", language: "Tajik" },
	{ code: "th", language: "Thai" },
	{ code: "ti", language: "Tigrinya" },
	{ code: "tk", language: "Turkmen" },
	{ code: "tl", language: "Tagalog" },
	{ code: "tn", language: "Tswana" },
	{ code: "to", language: "Tonga" },
	{ code: "tr", language: "Turkish" },
	{ code: "ts", language: "Tsonga" },
	{ code: "tt", language: "Tatar" },
	{ code: "tw", language: "Twi" },
	{ code: "ty", language: "Tahitian" },
	{ code: "ug", language: "Uighur" },
	{ code: "uk", language: "Ukrainian" },
	{ code: "ur", language: "Urdu" },
	{ code: "uz", language: "Uzbek" },
	{ code: "ve", language: "Venda" },
	{ code: "vi", language: "Vietnamese" },
	{ code: "vo", language: "Volapük" },
	{ code: "wa", language: "Walloon" },
	{ code: "wo", language: "Wolof" },
	{ code: "xh", language: "Xhosa" },
	{ code: "yi", language: "Yiddish" },
	{ code: "yo", language: "Yoruba" },
	{ code: "za", language: "Zhuang" },
	{ code: "zh", language: "Chinese" },
	{ code: "zu", language: "Zulu" },
] as const;
export type Language = (typeof languages)[number];

// Language code
export const languageCodeOptions = [
	"aa",
	"ab",
	"ae",
	"af",
	"ak",
	"am",
	"an",
	"ar",
	"as",
	"av",
	"ay",
	"az",
	"ba",
	"be",
	"bg",
	"bh",
	"bi",
	"bm",
	"bn",
	"bo",
	"br",
	"bs",
	"ca",
	"ce",
	"ch",
	"co",
	"cr",
	"cs",
	"cu",
	"cv",
	"cy",
	"da",
	"de",
	"dv",
	"dz",
	"ee",
	"el",
	"en",
	"eo",
	"es",
	"et",
	"eu",
	"fa",
	"ff",
	"fi",
	"fj",
	"fo",
	"fr",
	"fy",
	"ga",
	"gd",
	"gl",
	"gn",
	"gu",
	"gv",
	"ha",
	"he",
	"hi",
	"ho",
	"hr",
	"ht",
	"hu",
	"hy",
	"hz",
	"ia",
	"id",
	"ie",
	"ig",
	"ii",
	"ik",
	"io",
	"is",
	"it",
	"iu",
	"ja",
	"jv",
	"ka",
	"kg",
	"ki",
	"kj",
	"kk",
	"kl",
	"km",
	"kn",
	"ko",
	"kr",
	"ks",
	"ku",
	"kv",
	"kw",
	"ky",
	"la",
	"lb",
	"lg",
	"li",
	"ln",
	"lo",
	"lt",
	"lu",
	"lv",
	"mg",
	"mh",
	"mi",
	"mk",
	"ml",
	"mn",
	"mr",
	"ms",
	"mt",
	"my",
	"na",
	"nb",
	"nd",
	"ne",
	"ng",
	"nl",
	"nn",
	"no",
	"nr",
	"nv",
	"ny",
	"oc",
	"oj",
	"om",
	"or",
	"os",
	"pa",
	"pi",
	"pl",
	"ps",
	"pt",
	"qu",
	"rm",
	"rn",
	"ro",
	"ru",
	"rw",
	"sa",
	"sc",
	"sd",
	"se",
	"sg",
	"si",
	"sk",
	"sl",
	"sm",
	"sn",
	"so",
	"sq",
	"sr",
	"ss",
	"st",
	"su",
	"sv",
	"sw",
	"ta",
	"te",
	"tg",
	"th",
	"ti",
	"tk",
	"tl",
	"tn",
	"to",
	"tr",
	"ts",
	"tt",
	"tw",
	"ty",
	"ug",
	"uk",
	"ur",
	"uz",
	"ve",
	"vi",
	"vo",
	"wa",
	"wo",
	"xh",
	"yi",
	"yo",
	"za",
	"zh",
	"zu",
] as const;
export type LanguageCode = (typeof languageCodeOptions)[number];
